// <auto-generated />
namespace ETConsole.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class nombre_bonito : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nombre_bonito));
        
        string IMigrationMetadata.Id
        {
            get { return "201307201925216_nombre_bonito"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
